# 默认设置
default:
  groupGlobalCD:  500    # 群聊中所有指令操作冷却时间，单位毫秒,0则无限制
  singleCD: 500   # 群聊中个人操作冷却时间，单位毫秒

  onlyReplyAt: 0   # 是否只仅关注主动@机器人的消息， 0-否 1-是 2-触发用户非主人只回复@机器人的消息及特定前缀的消息，主人免前缀
  botAlias:        # 开启后则只回复@机器人的消息及特定前缀的消息，支持多个
    - 葵崽
    - 葵葵   
  
  addPrivate: 1    #是否允许私聊添加  1-允许 0-禁止
  addLimit: 0      # 添加权限 0-所有人 1-管理员 2-仅主人
  addReply: false  # 添加后是否回复
  addAt: false     # 添加回复是否@用户
  addRecall: 0     # 添加回复撤回时间(秒)，0不撤回

  enable: []       #只启用功能，配置后只有该功能才响应

  #禁用功能，功能名称,例如：帮助
  disable: []      # 禁用功能列表

# 群单独设置，自动覆盖默认值
123456:
  groupGlobalCD:  0    # 群聊中所有指令操作冷却时间，单位毫秒,0则无限制
  singleCD: 1000   # 群聊中个人操作冷却时间，单位毫秒
