# 复制为 config.yaml 可覆盖
browserType: chromium
chromiumPath: ""
wsEndpoint: ""
channel: ""
headless: true
args:
  - --no-sandbox
  - --disable-setuid-sandbox
  - --disable-dev-shm-usage
  - --disable-gpu
playwrightTimeout: 120000
healthCheckInterval: 60000
maxRetries: 3
retryDelay: 2000
restartNum: 150
viewport:
  width: 1280
  height: 720
  deviceScaleFactor: 1
contextOptions:
  bypassCSP: true
  reducedMotion: reduce
