# 复制为 config.yaml 可覆盖
headless: "new"
chromiumPath: ""
wsEndpoint: ""
args:
  - --no-sandbox
  - --disable-setuid-sandbox
  - --disable-dev-shm-usage
  - --disable-gpu
puppeteerTimeout: 120000
restartNum: 150
viewport:
  width: 1280
  height: 720
  deviceScaleFactor: 1
